package org.example;


import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

public class DnaTest {
    @ParameterizedTest
    @MethodSource("dataDna")
    public void testDna(String dna, int[] expected) {
        int[] actual = Dna.calc(dna);
        Assertions.assertArrayEquals(expected, actual);
    }

    private static Stream<Arguments> dataDna() {
        int[] expected1 = {20, 12, 17, 21};
        int[] expected2 = {206, 223, 237, 229};
        return Stream.of(
                Arguments.of("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC", expected1),
                Arguments.of("GTCCCGTATAGCCTTTCATGTGAGATTATAAAATAGGGCGTCAGTGTCGATGCCAGGTCAGTGCGGCGTAGGGACCACAGGTGACACCAGACGTTCGTTCCCACCACGACTCGCAGTAGGTCCTAGTCTTGGTTACCTGAACGAGGTCGCATATTTGAATCGGAGCGGACGTGACCCACATTATTTATGATGCCTTTTATGCGGTGTACCCACGCTATTAGTCGCAACTAAATGGTGCCCGTTTTAACTGGGGGCGCAACTACCGACGGTTGCATTTAAGCTCAAGGGCCTCTGACCTAGAGACACGCACGAGTAGTCCGTGCTAATGAAGACCTGTAACTGGCCTCTTACACGCCGTGCTTCGTAGCGATGGAGATCGCCATACTTATCTAATCGCGACTAGCCATGTCCTTTTGTTACTACGAGTGTCGGCGCAGCACGCTAGAGGAGGAGTTGAATTTTTCGTGCCACAAGGCTAGATCGTGCAAGGCTCTCATTGAAACCGAAGCCTCTTTGCACGGTTAGTCCGATAAACCTAATGGTACTTATGGGAGCCAACCTCCGGCTGCCTTCCGCCTTAAGATCCTTTACATTGTTGTTTCCGAATCACGTAGTACCCGCATACTTGCGGGGCACGTGTACTTTCTTGGAATTGATGACCATTTTGTGTGCACGGATTTAGCGCAGTAGAGTGTACGTGCATTTAAATGAGCGTATATATGACAGTAAGCCGGGTAAGTAACGGGTGCTCCGAGCCTATTAAGCCCCGGTGCGGGGTGCGCTGCATGGCGTAACCCGAACAATTCGAGATCGAGGAAGAAAGCGAGGCGAATGTTCCACCGAGCCCTGGGCAACCTCCAGTCTGTCGGCTGTACAGTATATCAGCTGCTCTGCT", expected2)
        );
    }
}
